apiVersion: v1
kind: Namespace
metadata:
  name: tulia

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: tulia-ui
  name: azure-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: tulia
    role: ui
  ports:
  - port: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tulia-frontend
  labels:
    app: tulia
    role: ui
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: tulia
      role: ui
  template:
    metadata:
      labels:
        app: tulia
        role: ui
    spec:
      imagePullSecrets:
      - name: tuliafront
      containers:
      - name: ui
        image: bacoordinationp3.azurecr.io/tulia/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80